// Deterministic PortableValue materialization for the plist profiles, plus
// the cross-representation conversion transform.
//
// Data authority:
//   - RFC 0004 §3-§8 (https://github.com/consema/consema/blob/main/docs/rfcs/0004-materialization-conversion-and-
//     structural-edit-v1.md): the common MaterializationRequest v1,
//     ExactOnly representability, the completion algebra, and the
//     provenance direction (portable input locations to the new Document).
//   - RFC 0013 §10 (https://github.com/consema/consema/blob/main/docs/rfcs/0013-plist-family-profiles-v1.md):
//     `plist.xml-canonical@1` (Apple header spelling, four-space
//     indentation, LF line endings, whole-second dates, base64 wrapped at
//     `76 - 8 * depth`, decimal integers, shortest-round-trip reals) and
//     `plist.binary-canonical@1` (minimal widths, negatives always 8 bytes,
//     Float32 width preserved, deduplicated scalars, minimal ref/offset
//     widths, sortVersion 0). Every style validates the complete input,
//     encodes, reparses the exact generated bytes, and compares the reparsed
//     native model to the promised input semantics.
//   - RFC 0013 §7 (https://github.com/consema/consema/blob/main/docs/rfcs/0013-plist-family-profiles-v1.md): conversion between the two
//     representations is exact when every native fact is expressible and
//     fails atomically otherwise; binary-only facts are UID values, Float32
//     width facts, unpaired-surrogate strings, fractional-second dates, and
//     shared object identity.
//   - conformance/vectors/plist-v1.json (plist.materialization.*,
//     plist.conversion.*) pins the golden output bytes and failure codes;
//     https://github.com/consema/consema-rs/blob/main/consema-plist/src/materialization.rs is the byte-arbitration
//     authority (record validation materialization.rs, expressibility
//     materialization.rs, XML writer materialization.rs,
//     binary writer materialization.rs);
//     document.rs pins the conversion transform.
//
// Kotlin-idiomatic design: a bounded output buffer wraps the JDK byte
// accumulation with explicit checked growth; the writers are single
// recursive classes with exhaustive `when` over the closed PortableValue
// kind set (the json-family precedent, kotlin/src/main/kotlin/consema/json/Materialization.kt).

package consema.plist

import consema.core.AssociationLocation
import consema.core.AssociationRole
import consema.core.Kind
import consema.core.PortableValue
import consema.core.PvArray
import consema.core.PvBinaryFloat32
import consema.core.PvBinaryFloat64
import consema.core.PvBoolean
import consema.core.PvBytes
import consema.core.PvDecimal
import consema.core.PvEntryMapping
import consema.core.PvInteger
import consema.core.PvObject
import consema.core.PvString
import consema.core.ValuePath
import consema.core.ValuePathSegment
import consema.document.CompleteMaterialization
import consema.document.FailedMaterializationAttempt
import consema.document.MaterializationException
import consema.document.MaterializationFailureKind
import consema.document.MaterializationFidelity
import consema.document.MaterializationInputLocation
import consema.document.MaterializationLimits
import consema.document.MaterializationProvenanceEntry
import consema.document.MaterializationProvenanceMap
import consema.document.MaterializationRelation
import consema.document.MaterializationReport
import consema.document.MaterializationRequest
import consema.document.MaterializationResult
import consema.document.MaterializedOrigin
import consema.document.NewlinePolicy
import consema.document.ParseLimits
import consema.document.SourceEncoding
import consema.protocol.DiagnosticCategory
import consema.protocol.Severity
import kotlin.math.absoluteValue

/** The frozen style identifiers (materialization.rs). */
private const val STYLE_XML = "plist.xml-canonical"

/** The frozen style identifiers (materialization.rs). */
private const val STYLE_BINARY = "plist.binary-canonical"

/** The value-tree record identifier (materialization.rs). */
private const val VALUE_TREE_RECORD = "plist.value-tree@1"

/** The truncation policy spelling (materialization.rs). */
private const val TRUNCATE_POLICY = "TruncateWithReport"


/** Seconds from the Unix epoch to 2001-01-01T00:00:00Z (RFC 0013 §5.5). */
private const val PLIST_EPOCH_OFFSET_UNIX: Double = 978307200.0

/** Exact-double decomposition bound for XML dates (materialization.rs). */
private const val EXACT_UNIX_SECONDS_BOUND: Double = 9_007_199_254_740_992.0

/** Negative-zero bit pattern (materialization.rs). */
private val NEGATIVE_ZERO_BITS: Long = java.lang.Double.doubleToRawLongBits(-0.0)

/** Materialization style (materialization.rs). */
internal enum class PlistMaterializationStyle {
    /** `plist.xml-canonical@1`: the Apple header spelling, four-space
     * indentation, LF line endings, whole-second dates (RFC 0013 §10.1). */
    Xml,

    /** `plist.binary-canonical@1`: minimal widths, deduplicated scalars,
     * `sortVersion = 0x00` (RFC 0013 §10.2). */
    Binary,
}

/** Stable materialization failure with the frozen code mapping
 * (materialization.rs). */
sealed class MaterializationFailure(val code: String) : Exception(code) {
    /** One complete input value cannot be represented; the payload names
     * the blocking fact. */
    data class Unrepresentable(val path: ValuePath, val kind: Kind) :
        MaterializationFailure(
            if (kind == Kind.Date) {
                PlistCodes.MATERIALIZATION_FRACTIONAL_DATE
            } else {
                PlistCodes.MATERIALIZATION_UNREPRESENTABLE
            },
        )

    /** Request fields contradict the record contract. */
    data class InvalidRequest(val reason: String) :
        MaterializationFailure("core.materialization.invalid-request@1")

    /** Target profile is unavailable. */
    data object UnsupportedProfile :
        MaterializationFailure("core.materialization.unsupported-profile@1")

    /** Style is unavailable for the target profile. */
    data object UnsupportedStyle :
        MaterializationFailure("core.materialization.unsupported-style@1")

    /** Encoding is unavailable for the target profile. */
    data object UnsupportedEncoding :
        MaterializationFailure("core.materialization.unsupported-encoding@1")

    /** Newline policy is unavailable for the selected style. */
    data object UnsupportedNewline :
        MaterializationFailure("core.materialization.unsupported-newline@1")

    /** A configured limit was reached. */
    data class ResourceLimit(val name: String) :
        MaterializationFailure(PlistCodes.MATERIALIZATION_RESOURCE_LIMIT)

    /** Generated bytes did not form the promised target document. */
    data object FormationFailed :
        MaterializationFailure("core.materialization.formation-failed@1")
}

/** One validated value record with its input path (materialization.rs
 *). */
private class ValueNode(val path: ValuePath, val kind: ValueKind)

/** One validated dictionary association (materialization.rs). */
private class DictEntry(val key: PlistString, val keyPath: ValuePath, val value: ValueNode)

/** Closed validated value kinds (materialization.rs). */
private sealed class ValueKind {
    class Dict(val entries: List<DictEntry>) : ValueKind()

    class Array(val elements: List<ValueNode>) : ValueKind()

    class StringV(val string: PlistString) : ValueKind()

    class Integer(val value: Long) : ValueKind()

    class Real(val real: PlistReal) : ValueKind()

    class BooleanV(val value: Boolean) : ValueKind()

    class Date(val seconds: Double) : ValueKind()

    class Data(val bytes: ByteArray) : ValueKind()

    class Uid(val value: Int) : ValueKind()
}

/**
 * Materializes one complete `plist.value-tree@1` record into a new
 * immutable plist document (RFC 0013 §10; materialization.rs). A
 * failure contains no Document, no partial bytes, and no provenance that
 * can be mistaken for a result (RFC 0004 §3).
 */
fun materialize(
    value: PortableValue,
    request: MaterializationRequest,
): MaterializationResult<Document> {
    val analyzed = ArrayList<ValuePath>()
    return try {
        MaterializationResult.Complete(materializeComplete(value, request, analyzed))
    } catch (e: MaterializationFailure) {
        MaterializationResult.Failed(
            FailedMaterializationAttempt(
                failure = toDocumentException(e),
                report = MaterializationReport.new(emptyList(), request.limits),
                analyzedInputPaths = analyzed,
            ),
        )
    }
}

/**
 * The frozen `plist.materialization.*@1` failure-code mapping of one shared
 * materialization failure (materialization.rs). The family codes stay
 * out of the core registry (RFC 0013 §12), so the plist-specific codes are
 * carried in the exception [MaterializationException.reason] by
 * [toDocumentException]; this function restores the exact code the vectors
 * assert (plist_v1.rs).
 */
fun materializationFailureCode(failure: MaterializationException): String {
    if (failure.reason == PlistCodes.MATERIALIZATION_FRACTIONAL_DATE) {
        return PlistCodes.MATERIALIZATION_FRACTIONAL_DATE
    }
    if (failure.reason == PlistCodes.MATERIALIZATION_RESOURCE_LIMIT) {
        return PlistCodes.MATERIALIZATION_RESOURCE_LIMIT
    }
    return failure.code
}

/** Maps one family failure to the shared materialization exception carrying
 * the frozen code (the vector failure-name surface). */
private fun toDocumentException(failure: MaterializationFailure): MaterializationException =
    when (failure) {
        is MaterializationFailure.Unrepresentable -> MaterializationException(
            MaterializationFailureKind.UNREPRESENTABLE,
            reason = if (failure.kind == Kind.Date) {
                PlistCodes.MATERIALIZATION_FRACTIONAL_DATE
            } else {
                PlistCodes.MATERIALIZATION_UNREPRESENTABLE
            },
            path = failure.path,
            valueKind = failure.kind,
        )
        is MaterializationFailure.InvalidRequest -> MaterializationException(
            MaterializationFailureKind.INVALID_REQUEST,
            reason = failure.reason,
        )
        MaterializationFailure.UnsupportedProfile -> MaterializationException(
            MaterializationFailureKind.UNSUPPORTED_PROFILE,
        )
        MaterializationFailure.UnsupportedStyle -> MaterializationException(
            MaterializationFailureKind.UNSUPPORTED_STYLE,
        )
        MaterializationFailure.UnsupportedEncoding -> MaterializationException(
            MaterializationFailureKind.UNSUPPORTED_ENCODING,
        )
        MaterializationFailure.UnsupportedNewline -> MaterializationException(
            MaterializationFailureKind.UNSUPPORTED_NEWLINE,
        )
        is MaterializationFailure.ResourceLimit -> MaterializationException(
            MaterializationFailureKind.RESOURCE_LIMIT,
            reason = PlistCodes.MATERIALIZATION_RESOURCE_LIMIT,
            name = failure.name,
        )
        MaterializationFailure.FormationFailed -> MaterializationException(
            MaterializationFailureKind.FORMATION_FAILED,
        )
    }

private fun materializeComplete(
    value: PortableValue,
    request: MaterializationRequest,
    analyzed: ArrayList<ValuePath>,
): CompleteMaterialization<Document> {
    val style = validateRequest(request)
    val limits = request.limits
    val record = validateRecord(value, request, analyzed)
    // The transformed root carries the authorized truncations; the writers
    // serialize the transformed tree, never the raw input record
    // (materialization.rs mutates the record in place).
    val (promised, events, transformed) = buildNative(record, style)
    val (bytes, items) = when (style) {
        PlistMaterializationStyle.Xml -> serializeXml(promised, limits)
        PlistMaterializationStyle.Binary -> serializeBinary(promised, limits)
    }
    val profile = when (style) {
        PlistMaterializationStyle.Xml -> PlistProfile.XmlV1
        PlistMaterializationStyle.Binary -> PlistProfile.BinaryV1
    }
    val formed = try {
        parse(bytes, profile, PlistEncodingSelection.ProfileDefault, parseLimits(limits))
    } catch (e: PlistFormationException) {
        throw MaterializationFailure.FormationFailed
    }
    if (formed.formationStatus != consema.document.FormationStatus.Complete ||
        !nativeEquals(promised, formed)
    ) {
        throw MaterializationFailure.FormationFailed
    }
    // The truncation events are family diagnostics (`plist.materialization.
    // fractional-date@1` is not a core-registry code, RFC 0013 §12); they are
    // carried on the target document's family diagnostic list, following the
    // HCL family precedent of family-owned diagnostics
    // (kotlin/src/main/kotlin/consema/hcl/Errors.kt). The transferable `core.diagnostic@1`
    // form is produced by PlistDiagnostic.toProtocolDiagnostic when a caller
    // supplies a stable source ID and an error-code registry.
    val target = if (events.isEmpty()) {
        formed
    } else {
        val truncationDiagnostics = ArrayList<PlistDiagnostic>(events.size)
        for ((index, event) in events.withIndex()) {
            truncationDiagnostics.add(
                PlistDiagnostic(
                    code = PlistCodes.MATERIALIZATION_FRACTIONAL_DATE,
                    category = DiagnosticCategory.Materialization,
                    severity = Severity.Info,
                    startByte = null,
                    endByte = null,
                    arguments = event,
                    notes = emptyList(),
                    occurrence = formed.diagnosticsList.size.toLong() + index.toLong(),
                ),
            )
        }
        Document(
            authority = formed.authority,
            source = formed.source,
            profile = formed.profile,
            losslessIndex = formed.losslessStructuralIndex(),
            binaryIndex = formed.binaryStructuralIndex(),
            formationStatus = formed.formationStatus,
            diagnosticsList = formed.diagnosticsList + truncationDiagnostics,
            entities = formed.entities,
            rootIndex = formed.rootIndex,
            nativeRoot = formed.nativeRoot,
            syntaxKinds = formed.losslessSyntaxKinds(),
            binaryFacts = formed.binaryFacts(),
            parseLimits = formed.parseLimits,
        )
    }
    val provenance = buildProvenance(items, target, limits)
    return CompleteMaterialization(
        document = target,
        fidelity = if (transformed) MaterializationFidelity.Transformed else MaterializationFidelity.Exact,
        report = MaterializationReport.new(emptyList(), limits),
        provenance = provenance,
    )
}

/** Validates the request against the frozen style contracts (RFC 0013 §10;
 * materialization.rs). */
private fun validateRequest(request: MaterializationRequest): PlistMaterializationStyle {
    val profile = request.targetProfile
    val style = request.style
    val selected = when {
        profile.id == "plist.xml" && profile.version == 1 &&
            style.id == STYLE_XML && style.version == 1 -> PlistMaterializationStyle.Xml

        profile.id == "plist.binary" && profile.version == 1 &&
            style.id == STYLE_BINARY && style.version == 1 -> PlistMaterializationStyle.Binary

        (profile.id != "plist.xml" && profile.id != "plist.binary") || profile.version != 1 ->
            throw MaterializationFailure.UnsupportedProfile

        else -> throw MaterializationFailure.UnsupportedStyle
    }
    when (selected) {
        PlistMaterializationStyle.Xml -> {
            if (request.encoding !== SourceEncoding.Utf8) {
                throw MaterializationFailure.UnsupportedEncoding
            }
            if (request.newline != NewlinePolicy.Lf) {
                throw MaterializationFailure.UnsupportedNewline
            }
        }
        PlistMaterializationStyle.Binary -> {
            if (request.encoding !== SourceEncoding.Binary) {
                throw MaterializationFailure.UnsupportedEncoding
            }
            if (request.newline != NewlinePolicy.None) {
                throw MaterializationFailure.UnsupportedNewline
            }
        }
    }
    return selected
}

/** Parse limits for the closure reparse, derived from the request
 * (materialization.rs). */
private fun parseLimits(limits: MaterializationLimits): PlistParseLimits = PlistParseLimits(
    common = ParseLimits(
        maxSourceBytes = limits.maxOutputBytes,
        maxNestingDepth = limits.maxDepth + 2,
        maxTokenCount = limits.maxOutputBytes,
        maxNodeCount = limits.maxInputNodes,
        maxDiagnostics = limits.maxReportEntries,
    ),
    maxDecodedUtf8Bytes = limits.maxOutputBytes * 3,
    maxDecodedScalars = limits.maxOutputBytes,
    maxObjectCount = limits.maxInputNodes * 2,
    maxContainerDepth = limits.maxDepth,
    maxDictEntries = limits.maxInputNodes,
    maxArrayElements = limits.maxInputNodes,
    maxDuplicateKeyGroupMembers = limits.maxInputNodes,
    maxStringCodeUnits = limits.maxOutputBytes,
    maxDataBytes = limits.maxOutputBytes,
    maxUidCount = limits.maxInputNodes,
    maxExtendedSizeIntegers = limits.maxInputNodes * 2,
    maxExtendedSizeValue = limits.maxInputNodes,
    maxOffsetIntSize = 8,
    maxObjectRefSize = 8,
    maxOffsetTableBytes = limits.maxOutputBytes * 8,
    maxSyntaxPieces = limits.maxOutputBytes,
    maxBinaryFacts = limits.maxOutputBytes * 16,
    maxConversionNodes = limits.maxInputNodes,
    maxReportEvents = limits.maxReportEntries,
    maxRecoveryRegions = limits.maxReportEntries,
)

/** Validates the record shape, the truncation policy, and the value tree
 * (materialization.rs). */
private fun validateRecord(
    value: PortableValue,
    request: MaterializationRequest,
    analyzed: ArrayList<ValuePath>,
): Record {
    analyzed.add(ValuePath.root())
    val objectValue = value as? PvObject
        ?: throw MaterializationFailure.InvalidRequest("input record is not plist.value-tree@1")
    val entries = objectValue.entries()
    if (entries.isEmpty() || entries[0].key != "record") {
        throw MaterializationFailure.InvalidRequest("input record is not plist.value-tree@1")
    }
    val recordValue = entries[0].value as? PvString
        ?: throw MaterializationFailure.InvalidRequest("input record is not plist.value-tree@1")
    if (recordValue.value != VALUE_TREE_RECORD) {
        throw MaterializationFailure.InvalidRequest("input record is not plist.value-tree@1")
    }
    val rootEntry = entries.firstOrNull { it.key == "root" }
        ?: throw MaterializationFailure.InvalidRequest("input record is not plist.value-tree@1")
    val policyEntry = entries.firstOrNull { it.key == "truncate_policy" }
    val policy = if (policyEntry == null) {
        false
    } else {
        val policyValue = policyEntry.value as? PvString
            ?: throw MaterializationFailure.Unrepresentable(
                ValuePath.root(), policyEntry.value.kind,
            )
        if (policyValue.value != TRUNCATE_POLICY) {
            throw MaterializationFailure.InvalidRequest("unsupported truncate policy")
        }
        true
    }
    val rootPath = ValuePath.root().child(ValuePathSegment.ObjectValue("root"))
    val root = validateValue(rootEntry.value, rootPath, request.limits, analyzed, 0)
    return Record(root, policy)
}

/** One validated `plist.value-tree@1` record (materialization.rs). */
private class Record(val root: ValueNode, val policy: Boolean)

private fun validateValue(
    value: PortableValue,
    path: ValuePath,
    limits: MaterializationLimits,
    analyzed: ArrayList<ValuePath>,
    depth: Int,
): ValueNode = ValueNode(path, validateKind(value, path, limits, analyzed, depth))

private fun validateKind(
    value: PortableValue,
    path: ValuePath,
    limits: MaterializationLimits,
    analyzed: ArrayList<ValuePath>,
    depth: Int,
): ValueKind {
    analyzed.add(path)
    val maxOutputBytes = limits.maxOutputBytes
    val kind: ValueKind = when (value) {
        is PvObject -> {
            val objectEntries = value.entries()
            if (objectEntries.any { it.key == "kind" }) {
                throw MaterializationFailure.Unrepresentable(path, Kind.Object)
            }
            val epoch = objectEntries.firstOrNull { it.key == "epoch" }
            val seconds = objectEntries.firstOrNull { it.key == "seconds" }
            if (epoch != null && seconds != null) {
                // Date leaf: exact double seconds plus the fixed epoch.
                val epochValue = epoch.value as? PvString
                    ?: throw MaterializationFailure.Unrepresentable(
                        path.child(ValuePathSegment.ObjectValue("epoch")), epoch.value.kind,
                    )
                if (epochValue.value != PLIST_EPOCH_SPELLING) {
                    throw MaterializationFailure.InvalidRequest(
                        "date epoch is not 2001-01-01T00:00:00Z",
                    )
                }
                val secondsValue = when (val member = seconds.value) {
                    is PvBinaryFloat64 -> member.toFloat()
                    is PvDecimal -> decimalToF64(member)
                        ?: throw MaterializationFailure.Unrepresentable(path, Kind.Date)
                    else -> throw MaterializationFailure.Unrepresentable(path, Kind.Date)
                }
                if (!secondsValue.isFinite()) {
                    throw MaterializationFailure.Unrepresentable(path, Kind.Date)
                }
                ValueKind.Date(secondsValue)
            } else {
                val uid = objectEntries.firstOrNull { it.key == "uid" }
                if (uid != null) {
                    val integer = uid.value as? PvInteger
                        ?: throw MaterializationFailure.Unrepresentable(
                            path.child(ValuePathSegment.ObjectValue("uid")), uid.value.kind,
                        )
                    val long = bigIntegerToLong(integer.value)
                        ?: throw MaterializationFailure.Unrepresentable(path, Kind.Integer)
                    val uidValue = long.toInt().takeIf { long in 0..0xFFFF_FFFFL }
                        ?: throw MaterializationFailure.Unrepresentable(path, Kind.Integer)
                    ValueKind.Uid(uidValue)
                } else {
                    val hex = objectEntries.firstOrNull { it.key == "hex" }
                    if (hex != null) {
                        val hexText = hex.value as? PvString
                            ?: throw MaterializationFailure.Unrepresentable(
                                path.child(ValuePathSegment.ObjectValue("hex")), hex.value.kind,
                            )
                        if (hexText.value.length / 2 > maxOutputBytes) {
                            throw MaterializationFailure.ResourceLimit("output-bytes")
                        }
                        val bytes = decodeHex(hexText.value)
                            ?: throw MaterializationFailure.Unrepresentable(path, Kind.String)
                        ValueKind.Data(bytes)
                    } else {
                        // A dictionary spelled as an ordered JSON object.
                        if (depth + 1 > limits.maxDepth) {
                            throw MaterializationFailure.ResourceLimit("input-depth")
                        }
                        val out = ArrayList<DictEntry>(objectEntries.size)
                        for ((ordinal, entry) in objectEntries.withIndex()) {
                            val keyPath = path.child(ValuePathSegment.EntryKey(ordinal.toLong()))
                            val valuePath = path.child(ValuePathSegment.EntryValue(ordinal.toLong()))
                            out.add(
                                DictEntry(
                                    PlistString.fromUnicode(entry.key),
                                    keyPath,
                                    validateValue(entry.value, valuePath, limits, analyzed, depth + 1),
                                ),
                            )
                        }
                        ValueKind.Dict(out)
                    }
                }
            }
        }
        is PvArray -> {
            if (depth + 1 > limits.maxDepth) {
                throw MaterializationFailure.ResourceLimit("input-depth")
            }
            val out = ArrayList<ValueNode>(value.items().size)
            for ((index, element) in value.items().withIndex()) {
                val elementPath = path.child(ValuePathSegment.SequenceElement(index.toLong()))
                out.add(validateValue(element, elementPath, limits, analyzed, depth + 1))
            }
            ValueKind.Array(out)
        }
        is PvEntryMapping -> {
            // Ordered dictionary associations; the projection emission keeps
            // duplicate keys and association order (RFC 0013 §9;
            // materialization.rs).
            if (depth + 1 > limits.maxDepth) {
                throw MaterializationFailure.ResourceLimit("input-depth")
            }
            val out = ArrayList<DictEntry>(value.size())
            for ((ordinal, entry) in value.entries().withIndex()) {
                val keyPath = path.child(ValuePathSegment.EntryKey(ordinal.toLong()))
                val key = entry.key as? PvString
                    ?: throw MaterializationFailure.Unrepresentable(keyPath, entry.key.kind)
                val valuePath = path.child(ValuePathSegment.EntryValue(ordinal.toLong()))
                out.add(
                    DictEntry(
                        PlistString.fromUnicode(key.value),
                        keyPath,
                        validateValue(entry.value, valuePath, limits, analyzed, depth + 1),
                    ),
                )
            }
            ValueKind.Dict(out)
        }
        is PvString -> {
            if (value.value.length > maxOutputBytes) {
                throw MaterializationFailure.ResourceLimit("output-bytes")
            }
            ValueKind.StringV(PlistString.fromUnicode(value.value))
        }
        is PvInteger -> {
            val long = bigIntegerToLong(value.value)
                ?: throw MaterializationFailure.Unrepresentable(path, Kind.Integer)
            ValueKind.Integer(long)
        }
        is PvBinaryFloat32 -> ValueKind.Real(PlistReal.single(value.bits))
        is PvBinaryFloat64 -> ValueKind.Real(PlistReal.double(value.bits))
        is PvDecimal -> {
            val real = decimalToF64(value)
                ?: throw MaterializationFailure.Unrepresentable(path, Kind.Decimal)
            ValueKind.Real(PlistReal.double(real.toBits()))
        }
        is PvBoolean -> ValueKind.BooleanV(value.value)
        is PvBytes -> {
            if (value.content().size > maxOutputBytes) {
                throw MaterializationFailure.ResourceLimit("output-bytes")
            }
            ValueKind.Data(value.content())
        }
        else -> throw MaterializationFailure.Unrepresentable(path, value.kind)
    }
    return kind
}

/** Converts one exact decimal to its double value; null when the
 * coefficient or exponent exceeds the exact i64 range (materialization.rs
 *). */
private fun decimalToF64(decimal: PvDecimal): Double? {
    val coefficient = bigIntegerToLong(decimal.coefficient) ?: return null
    val exponent = bigIntegerToLong(decimal.exponent) ?: return null
    var value = coefficient.toDouble()
    if (exponent >= 0) {
        for (i in 0 until exponent.toInt().coerceAtMost(400)) {
            value *= 10.0
        }
    } else {
        for (i in 0 until (-exponent).toInt().coerceAtMost(400)) {
            value /= 10.0
        }
    }
    return value
}

/** Builds the promised native model with the style expressibility rules
 * (RFC 0013 §7, §10; materialization.rs). Returns the record tree,
 * the truncation events, and whether the operation was transformed. */
private fun buildNative(
    record: Record,
    style: PlistMaterializationStyle,
): Triple<ValueNode, List<Map<String, String>>, Boolean> {
    val events = ArrayList<Map<String, String>>()
    var transformed = false
    val root = buildValue(record.root, style, record.policy, events, transformedRef = { transformed = it })
    return Triple(root, events, transformed)
}

private fun buildValue(
    node: ValueNode,
    style: PlistMaterializationStyle,
    policy: Boolean,
    events: ArrayList<Map<String, String>>,
    transformedRef: (Boolean) -> Unit,
): ValueNode {
    val kind = when (val kind = node.kind) {
        is ValueKind.Dict -> {
            val entries = kind.entries.map { entry ->
                if (style == PlistMaterializationStyle.Xml && !isXmlText(entry.key.codeUnits())) {
                    throw MaterializationFailure.Unrepresentable(entry.keyPath, Kind.String)
                }
                DictEntry(
                    entry.key,
                    entry.keyPath,
                    buildValue(entry.value, style, policy, events, transformedRef),
                )
            }
            ValueKind.Dict(entries)
        }
        is ValueKind.Array -> {
            val elements = kind.elements.map {
                buildValue(it, style, policy, events, transformedRef)
            }
            ValueKind.Array(elements)
        }
        is ValueKind.StringV -> {
            if (style == PlistMaterializationStyle.Xml &&
                (kind.string.status == PlistStringStatus.UnpairedSurrogate ||
                    !isXmlText(kind.string.codeUnits()))
            ) {
                throw MaterializationFailure.Unrepresentable(node.path, Kind.String)
            }
            kind
        }
        is ValueKind.Integer -> kind
        is ValueKind.Real -> {
            if (style == PlistMaterializationStyle.Xml) {
                if (kind.real.width == RealWidth.Float32) {
                    throw MaterializationFailure.Unrepresentable(node.path, Kind.BinaryFloat32)
                }
                if (!realExpressible(kind.real)) {
                    throw MaterializationFailure.Unrepresentable(node.path, Kind.BinaryFloat64)
                }
            }
            kind
        }
        is ValueKind.BooleanV -> kind
        is ValueKind.Date -> {
            if (style == PlistMaterializationStyle.Xml) {
                if (kind.seconds.toRawBits() == NEGATIVE_ZERO_BITS) {
                    throw MaterializationFailure.Unrepresentable(node.path, Kind.Date)
                }
                val whole = wholeSecondDate(kind.seconds)
                if (whole == null) {
                    if (!policy) {
                        throw MaterializationFailure.Unrepresentable(node.path, Kind.Date)
                    }
                    val original = kind.seconds
                    val truncated = truncTowardZero(original)
                    if (truncated.toRawBits() == NEGATIVE_ZERO_BITS || wholeSecondDate(truncated) == null) {
                        throw MaterializationFailure.Unrepresentable(node.path, Kind.Date)
                    }
                    events.add(
                        mapOf(
                            "path" to node.path.toString(),
                            "original" to original.toString(),
                            "truncated" to truncated.toString(),
                        ),
                    )
                    transformedRef(true)
                    ValueKind.Date(truncated)
                } else {
                    kind
                }
            } else {
                kind
            }
        }
        is ValueKind.Data -> kind
        is ValueKind.Uid -> {
            if (style == PlistMaterializationStyle.Xml) {
                throw MaterializationFailure.Unrepresentable(node.path, Kind.BinaryFloat32)
            }
            kind
        }
    }
    return ValueNode(node.path, kind)
}

/** Whether the exact bits of one real survive the XML spelling
 * (materialization.rs). */
private fun realExpressible(real: PlistReal): Boolean {
    val value = real.asDouble()
    return if (value.isNaN()) {
        value.toRawBits() == java.lang.Double.doubleToRawLongBits(Double.NaN)
    } else if (value.isInfinite()) {
        true
    } else {
        value.toString().toDoubleOrNull()?.toRawBits() == value.toRawBits()
    }
}

/** Whether every scalar of one well-formed UTF-16 sequence is an XML 1.0
 * character (materialization.rs). */
private fun isXmlText(units: IntArray): Boolean {
    var index = 0
    while (index < units.size) {
        val unit = units[index]
        val scalar = if (unit in 0xD800..0xDBFF) {
            if (index + 1 < units.size && units[index + 1] in 0xDC00..0xDFFF) {
                index += 2
                0x1_0000 + ((unit - 0xD800) shl 10) + (units[index - 1] - 0xDC00)
            } else {
                return false
            }
        } else if (unit in 0xDC00..0xDFFF) {
            return false
        } else {
            index += 1
            unit
        }
        if (scalar != 0x9 && scalar != 0xA && scalar != 0xD &&
            !(scalar in 0x20..0xD7FF) && !(scalar in 0xE000..0xFFFD) &&
            !(scalar in 0x1_0000..0x10_FFFF)
        ) {
            return false
        }
    }
    return true
}

/** Decomposes exact plist-epoch seconds into XML calendar fields
 * (materialization.rs). */
private fun wholeSecondDate(seconds: Double): DateFields? {
    if (seconds % 1.0 != 0.0) {
        return null
    }
    val unix = seconds + PLIST_EPOCH_OFFSET_UNIX
    if (kotlin.math.abs(unix) >= EXACT_UNIX_SECONDS_BOUND) {
        return null
    }
    val unixInt = unix.toLong()
    val days = Math.floorDiv(unixInt, 86_400L)
    val secondsOfDay = Math.floorMod(unixInt, 86_400L)
    val (year, month, day) = civilFromDays(days)
    if (year.absoluteValue > 0xFFFF_FFFFL) {
        return null
    }
    return DateFields(
        year = year,
        month = month,
        day = day,
        hour = secondsOfDay / 3_600,
        minute = (secondsOfDay % 3_600) / 60,
        second = secondsOfDay % 60,
    )
}

private data class DateFields(val year: Long, val month: Long, val day: Long, val hour: Long, val minute: Long, val second: Long)

/** Proleptic Gregorian calendar date of `days` since the Unix epoch
 * (materialization.rs). */
private fun civilFromDays(days: Long): Triple<Long, Long, Long> {
    val z = days + 719_468
    val era = if (z >= 0) z else z - 146_096
    val eraNormalized = era / 146_097
    val dayOfEra = z - eraNormalized * 146_097
    val yearOfEra =
        (dayOfEra - dayOfEra / 1_460 + dayOfEra / 36_524 - dayOfEra / 146_096) / 365
    var year = yearOfEra + eraNormalized * 400
    val dayOfYear = dayOfEra - (365 * yearOfEra + yearOfEra / 4 - yearOfEra / 100)
    val monthPrime = (5 * dayOfYear + 2) / 153
    val day = dayOfYear - (153 * monthPrime + 2) / 5 + 1
    val month = monthPrime + if (monthPrime < 10) 3 else -9
    year += if (month <= 2) 1 else 0
    return Triple(year, month, day)
}

/** Whole-second XML date spelling (RFC 0013 §4.7; materialization.rs
 * 1275). */
private fun renderDate(fields: DateFields): String {
    val sign = if (fields.year < 0) "-" else ""
    return String.format(
        java.util.Locale.ROOT,
        "%s%04d-%02d-%02dT%02d:%02d:%02dZ",
        sign, fields.year.absoluteValue, fields.month, fields.day,
        fields.hour, fields.minute, fields.second,
    )
}

/** Deterministic shortest-round-trip decimal spelling of one real
 * (materialization.rs). */
private fun renderReal(real: PlistReal): String {
    val value = real.asDouble()
    return when {
        value.isNaN() -> "nan"
        value.isInfinite() -> if (negativeSign(value)) "-inf" else "inf"
        else -> value.toString()
    }
}

/** Hex decode of the data-leaf vector spelling; null on malformed hex. */
private fun decodeHex(hex: String): ByteArray? {
    if (hex.length % 2 != 0) {
        return null
    }
    val output = ByteArray(hex.length / 2)
    for (index in output.indices) {
        val high = hex[index * 2].digitToIntOrNull(16) ?: return null
        val low = hex[index * 2 + 1].digitToIntOrNull(16) ?: return null
        output[index] = ((high shl 4) or low).toByte()
    }
    return output
}

// ---------------------------------------------------------------------------
// XML writer (RFC 0013 §10.1; materialization.rs)
// ---------------------------------------------------------------------------

private data class InputItem(val path: ValuePath, val target: Int)

private class XmlWriter(
    private val limits: MaterializationLimits,
    private val out: StringBuilder = StringBuilder(),
    private val items: ArrayList<InputItem> = ArrayList(),
) {
    private var rank = 0

    fun write(root: ValueNode): ByteArray {
        out.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        out.append("<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n")
        out.append("<plist version=\"1.0\">\n")
        emitValue(root, 1)
        out.append("</plist>\n")
        checkOutput()
        return out.toString().toByteArray(Charsets.UTF_8)
    }

    private fun checkOutput() {
        if (out.length > limits.maxOutputBytes) {
            throw MaterializationFailure.ResourceLimit("output-bytes")
        }
    }

    private fun writeIndent(depth: Int) {
        repeat(depth) { out.append("    ") }
    }

    private fun emitValue(node: ValueNode, depth: Int) {
        when (val kind = node.kind) {
            is ValueKind.Dict -> {
                writeIndent(depth)
                if (kind.entries.isEmpty()) {
                    out.append("<dict></dict>\n")
                } else {
                    out.append("<dict>\n")
                    for (entry in kind.entries) {
                        writeIndent(depth + 1)
                        out.append("<key>")
                        escapeXmlText(entry.key.toUnicode()
                            ?: throw MaterializationFailure.Unrepresentable(entry.keyPath, Kind.String))
                        out.append("</key>\n")
                        emitValue(entry.value, depth + 1)
                    }
                    writeIndent(depth)
                    out.append("</dict>\n")
                }
            }
            is ValueKind.Array -> {
                writeIndent(depth)
                if (kind.elements.isEmpty()) {
                    out.append("<array></array>\n")
                } else {
                    out.append("<array>\n")
                    for (element in kind.elements) {
                        emitValue(element, depth + 1)
                    }
                    writeIndent(depth)
                    out.append("</array>\n")
                }
            }
            is ValueKind.StringV -> {
                writeIndent(depth)
                out.append("<string>")
                escapeXmlText(kind.string.toUnicode()
                    ?: throw MaterializationFailure.Unrepresentable(node.path, Kind.String))
                out.append("</string>\n")
            }
            is ValueKind.Integer -> {
                writeIndent(depth)
                out.append("<integer>")
                out.append(kind.value.toString())
                out.append("</integer>\n")
            }
            is ValueKind.Real -> {
                writeIndent(depth)
                out.append("<real>")
                out.append(renderReal(kind.real))
                out.append("</real>\n")
            }
            is ValueKind.BooleanV -> {
                writeIndent(depth)
                out.append(if (kind.value) "<true/>\n" else "<false/>\n")
            }
            is ValueKind.Date -> {
                writeIndent(depth)
                out.append("<date>")
                out.append(renderDate(wholeSecondDate(kind.seconds)
                    ?: throw MaterializationFailure.FormationFailed))
                out.append("</date>\n")
            }
            is ValueKind.Data -> {
                writeIndent(depth)
                out.append("<data>")
                out.append(encodeBase64Wrapped(kind.bytes, depth))
                out.append("</data>\n")
            }
            is ValueKind.Uid -> throw MaterializationFailure.FormationFailed
        }
        items.add(InputItem(node.path, rank))
        rank += 1
        checkOutput()
    }

    /** Escapes XML text content (RFC 0013 §4.9, §10.1): `&`, `<`, `>`, and a
     * literal CR (materialization.rs). */
    private fun escapeXmlText(text: String) {
        for (character in text) {
            when (character) {
                '&' -> out.append("&amp;")
                '<' -> out.append("&lt;")
                '>' -> out.append("&gt;")
                '\r' -> out.append("&#13;")
                else -> out.append(character)
            }
        }
    }

    /** Standard base64 with `=` padding wrapped at `76 - 8 * depth`
     * characters per line (RFC 0013 §4.8; materialization.rs). */
    private fun encodeBase64Wrapped(bytes: ByteArray, depth: Int): String {
        val budget = (76 - 8 * depth).coerceAtLeast(1)
        val alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
        val out2 = StringBuilder(bytes.size * 4 / 3 + 4)
        var line = 0
        var index = 0
        while (index < bytes.size) {
            val first = bytes[index].toInt() and 0xFF
            val second = if (index + 1 < bytes.size) bytes[index + 1].toInt() and 0xFF else 0
            val third = if (index + 2 < bytes.size) bytes[index + 2].toInt() and 0xFF else 0
            val chunkLen = minOf(3, bytes.size - index)
            if (line + 4 > budget && line > 0) {
                out2.append('\n')
                writeIndent(depth)
                line = 0
            }
            out2.append(alphabet[first ushr 2])
            out2.append(alphabet[((first and 0x03) shl 4) or (second ushr 4)])
            out2.append(if (chunkLen > 1) alphabet[((second and 0x0F) shl 2) or (third ushr 6)] else '=')
            out2.append(if (chunkLen > 2) alphabet[third and 0x3F] else '=')
            line += 4
            index += 3
        }
        return out2.toString()
    }

    fun items(): List<InputItem> = items
}

private fun serializeXml(root: ValueNode, limits: MaterializationLimits): Pair<ByteArray, List<InputItem>> {
    val writer = XmlWriter(limits)
    val bytes = writer.write(root)
    return bytes to writer.items()
}

// ---------------------------------------------------------------------------
// Binary writer (RFC 0013 §10.2; materialization.rs)
// ---------------------------------------------------------------------------

/** One planned binary object; scalars are deduplicated at first occurrence
 * (materialization.rs). */
private sealed class PlannedObject {
    class Dict(val keys: MutableList<Int>, val values: MutableList<Int>) : PlannedObject()

    class Array(val elements: MutableList<Int>) : PlannedObject()

    class Scalar(val key: ScalarKey) : PlannedObject()
}

/** One scalar key of the dedup cache (materialization.rs). */
private sealed class ScalarKey {
    class StringV(val string: PlistString) : ScalarKey()

    class Integer(val value: Long) : ScalarKey()

    class Real(val real: PlistReal) : ScalarKey()

    class BooleanV(val value: Boolean) : ScalarKey()

    class Date(val bits: Long) : ScalarKey()

    class Data(val bytes: ByteArray) : ScalarKey()

    class Uid(val value: Int) : ScalarKey()

    /** Identical scalar objects (string, integer, real, date, data)
     * deduplicate (RFC 0013 §5.12). */
    fun deduplicates(): Boolean = this !is BooleanV && this !is Uid

    override fun equals(other: Any?): Boolean = when {
        this === other -> true
        other !is ScalarKey -> false
        this is StringV && other is StringV -> string == other.string
        this is Integer && other is Integer -> value == other.value
        this is Real && other is Real -> real == other.real
        this is BooleanV && other is BooleanV -> value == other.value
        this is Date && other is Date -> bits == other.bits
        this is Data && other is Data -> bytes.contentEquals(other.bytes)
        this is Uid && other is Uid -> value == other.value
        else -> false
    }

    override fun hashCode(): Int = when (this) {
        is StringV -> string.hashCode()
        is Integer -> value.hashCode()
        is Real -> real.hashCode()
        is BooleanV -> value.hashCode()
        is Date -> bits.hashCode()
        is Data -> bytes.contentHashCode()
        is Uid -> value.hashCode()
    }
}

private class BinaryPlan {
    val objects = ArrayList<PlannedObject>()
    val items = ArrayList<InputItem>()
}

private fun planBinary(root: ValueNode): BinaryPlan {
    fun planNode(node: ValueNode, plan: BinaryPlan, cache: HashMap<ScalarKey, Int>): Int {
        return when (val kind = node.kind) {
            is ValueKind.Dict -> {
                val index = plan.objects.size
                plan.objects.add(PlannedObject.Dict(ArrayList(), ArrayList()))
                plan.items.add(InputItem(node.path, index))
                val keyRefs = ArrayList<Int>(kind.entries.size)
                for (entry in kind.entries) {
                    val key = ScalarKey.StringV(entry.key)
                    val keyIndex = cache.getOrPut(key) {
                        val at = plan.objects.size
                        plan.objects.add(PlannedObject.Scalar(key))
                        at
                    }
                    keyRefs.add(keyIndex)
                }
                val valueRefs = ArrayList<Int>(kind.entries.size)
                for (entry in kind.entries) {
                    valueRefs.add(planNode(entry.value, plan, cache))
                }
                val dict = plan.objects[index] as PlannedObject.Dict
                dict.keys.addAll(keyRefs)
                dict.values.addAll(valueRefs)
                index
            }
            is ValueKind.Array -> {
                val index = plan.objects.size
                plan.objects.add(PlannedObject.Array(ArrayList()))
                plan.items.add(InputItem(node.path, index))
                val elements = plan.objects[index] as PlannedObject.Array
                for (element in kind.elements) {
                    elements.elements.add(planNode(element, plan, cache))
                }
                index
            }
            else -> {
                val key = scalarKeyOf(node)
                if (key.deduplicates()) {
                    cache[key]?.let { cached ->
                        plan.items.add(InputItem(node.path, cached))
                        return cached
                    }
                }
                val index = plan.objects.size
                plan.objects.add(PlannedObject.Scalar(key))
                if (key.deduplicates()) {
                    cache[key] = index
                }
                plan.items.add(InputItem(node.path, index))
                index
            }
        }
    }
    val plan = BinaryPlan()
    planNode(root, plan, HashMap())
    return plan
}

private fun scalarKeyOf(node: ValueNode): ScalarKey =
    when (val kind = node.kind) {
        is ValueKind.StringV -> ScalarKey.StringV(kind.string)
        is ValueKind.Integer -> ScalarKey.Integer(kind.value)
        is ValueKind.Real -> ScalarKey.Real(kind.real)
        is ValueKind.BooleanV -> ScalarKey.BooleanV(kind.value)
        is ValueKind.Date -> ScalarKey.Date(kind.seconds.toRawBits())
        is ValueKind.Data -> ScalarKey.Data(kind.bytes)
        is ValueKind.Uid -> ScalarKey.Uid(kind.value)
        else -> throw MaterializationFailure.FormationFailed
    }

private fun serializeBinary(root: ValueNode, limits: MaterializationLimits): Pair<ByteArray, List<InputItem>> {
    val plan = planBinary(root)
    val numObjects = plan.objects.size
    val refSize = refSizeFor(numObjects)
    val out = ArrayList<Byte>(8 + 1024)
    "bplist00".forEach { out.add(it.code.toByte()) }
    val offsets = ArrayList<Int>(numObjects)
    for (planned in plan.objects) {
        offsets.add(out.size)
        writePlannedObject(out, planned, refSize)
        if (out.size > limits.maxOutputBytes) {
            throw MaterializationFailure.ResourceLimit("output-bytes")
        }
    }
    val offsetTableOffset = out.size
    val offsetIntSize = refSizeFor(offsetTableOffset)
    for (offset in offsets) {
        writeBe(out, offset.toLong(), offsetIntSize)
    }
    repeat(5) { out.add(0) }
    out.add(0) // sortVersion
    out.add(offsetIntSize.toByte())
    out.add(refSize.toByte())
    writeBe(out, numObjects.toLong(), 8)
    writeBe(out, 0, 8) // topObject: the root value is always object 0
    writeBe(out, offsetTableOffset.toLong(), 8)
    return out.toByteArray() to plan.items
}

private fun writePlannedObject(out: ArrayList<Byte>, planned: PlannedObject, refSize: Int) {
    when (planned) {
        is PlannedObject.Dict -> {
            val count = planned.keys.size
            writeSized(out, 0xD0, count)
            for (key in planned.keys) {
                writeBe(out, key.toLong(), refSize)
            }
            for (entry in planned.values) {
                writeBe(out, entry.toLong(), refSize)
            }
        }
        is PlannedObject.Array -> {
            val count = planned.elements.size
            writeSized(out, 0xA0, count)
            for (element in planned.elements) {
                writeBe(out, element.toLong(), refSize)
            }
        }
        is PlannedObject.Scalar -> writeScalar(out, planned.key)
    }
}

private fun writeScalar(out: ArrayList<Byte>, key: ScalarKey) {
    when (key) {
        is ScalarKey.StringV -> writeStringObject(out, key.string)
        is ScalarKey.Integer -> {
            val width = integerWidth(key.value)
            out.add((0x10 or java.lang.Integer.numberOfTrailingZeros(width)).toByte())
            writeBe(out, key.value.toULong().toLong(), width)
        }
        is ScalarKey.Real -> when (key.real.width) {
            RealWidth.Float64 -> {
                out.add(0x23)
                writeBe(out, key.real.bits, 8)
            }
            RealWidth.Float32 -> {
                out.add(0x22)
                writeBe(out, key.real.bits, 4)
            }
        }
        is ScalarKey.BooleanV -> out.add(if (key.value) 0x09 else 0x08)
        is ScalarKey.Date -> {
            out.add(0x33)
            writeBe(out, key.bits, 8)
        }
        is ScalarKey.Data -> {
            writeSized(out, 0x40, key.bytes.size)
            for (byte in key.bytes) {
                out.add(byte)
            }
        }
        is ScalarKey.Uid -> {
            val value = key.value.toLong() and 0xFFFF_FFFFL
            val width = uidWidth(value)
            out.add((0x80 or (width - 1)).toByte())
            writeBe(out, value, width)
        }
    }
}

/** Writes one string object: the ASCII marker when every code unit is below
 * `0x80`, else the UTF-16BE marker (RFC 0013 §5.6; materialization.rs
 * 1541). */
private fun writeStringObject(out: ArrayList<Byte>, string: PlistString) {
    val units = string.codeUnits()
    if (units.all { it < 0x80 }) {
        writeSized(out, 0x50, units.size)
        for (unit in units) {
            out.add(unit.toByte())
        }
    } else {
        writeSized(out, 0x60, units.size)
        for (unit in units) {
            out.add((unit ushr 8).toByte())
            out.add(unit.toByte())
        }
    }
}

/** Writes one sized marker; counts of 15 or more use the extended-size
 * sentinel (RFC 0013 §5.4; materialization.rs). */
private fun writeSized(out: ArrayList<Byte>, marker: Int, count: Int) {
    if (count < 0x0F) {
        out.add((marker or count).toByte())
        return
    }
    out.add((marker or 0x0F).toByte())
    val width = unsignedWidth(count.toLong())
    out.add((0x10 or java.lang.Integer.numberOfTrailingZeros(width)).toByte())
    writeBe(out, count.toLong(), width)
}

/** Appends one big-endian unsigned value of exactly `width` bytes. */
private fun writeBe(out: ArrayList<Byte>, value: Long, width: Int) {
    for (shift in (0 until width).reversed()) {
        out.add(((value ushr (8 * shift)) and 0xFF).toByte())
    }
}

/** Smallest width in bytes whose capacity exceeds `maxIndex`
 * (materialization.rs). */
private fun refSizeFor(maxIndex: Int): Int {
    var size = 1
    var capacity = 256L
    while (maxIndex >= capacity && size < 8) {
        size += 1
        capacity = if (capacity > Long.MAX_VALUE / 256) Long.MAX_VALUE else capacity * 256
    }
    return size
}

/** Minimal marker width for one signed 64-bit integer: negatives always use
 * the signed 8-byte form (materialization.rs). */
private fun integerWidth(value: Long): Int =
    if (value >= 0) unsignedWidth(value) else 8

/** Minimal marker width for one unsigned count (materialization.rs
 * 1604). */
private fun unsignedWidth(value: Long): Int =
    when {
        value <= 0xFF -> 1
        value <= 0xFFFF -> 2
        value <= 0xFFFF_FFFFL -> 4
        else -> 8
    }

/** Minimal byte width of one unsigned 32-bit UID (materialization.rs
 * 1617). */
private fun uidWidth(value: Long): Int =
    when {
        value <= 0xFF -> 1
        value <= 0xFFFF -> 2
        value <= 0xFF_FFFF -> 3
        else -> 4
    }

// ---------------------------------------------------------------------------
// Reparse closure and provenance
// ---------------------------------------------------------------------------

/** Compares the promised record tree against the reparsed target document
 * (RFC 0013 §10.3; materialization.rs). */
private fun nativeEquals(promised: ValueNode, document: Document): Boolean {
    val root = document.rootIndex
    return nativeNodeEquals(promised, document, root)
}

private fun nativeNodeEquals(node: ValueNode, document: Document, index: Int): Boolean {
    val native = document.valueEntity(index).native ?: return false
    return when (val kind = node.kind) {
        is ValueKind.Dict -> {
            val dict = native as? NativeValue.Dict ?: return false
            if (dict.entries.size != kind.entries.size) return false
            for ((position, entry) in kind.entries.withIndex()) {
                val entryEntity = document.dictEntryEntity(dict.entries[position])
                val keyNative = document.valueEntity(entryEntity.keyIndex).native
                    as? NativeValue.StringV ?: return false
                if (keyNative.string != entry.key) return false
                if (!nativeNodeEquals(entry.value, document, entryEntity.valueIndex)) return false
            }
            true
        }
        is ValueKind.Array -> {
            val array = native as? NativeValue.Array ?: return false
            if (array.elements.size != kind.elements.size) return false
            for ((position, element) in kind.elements.withIndex()) {
                val elementEntity = document.arrayElementEntity(array.elements[position])
                if (!nativeNodeEquals(element, document, elementEntity.valueIndex)) return false
            }
            true
        }
        is ValueKind.StringV -> {
            val string = native as? NativeValue.StringV ?: return false
            string.string == kind.string
        }
        is ValueKind.Integer -> native == NativeValue.Integer(kind.value)
        is ValueKind.Real -> native == NativeValue.Real(kind.real)
        is ValueKind.BooleanV -> native == NativeValue.BooleanV(kind.value)
        is ValueKind.Date -> native == NativeValue.Date(kind.seconds)
        is ValueKind.Data -> native == NativeValue.Data(PlistData.fromBytes(kind.bytes))
        is ValueKind.Uid -> native == NativeValue.Uid(PlistUid(kind.value))
    }
}

/** Builds the input-to-target provenance map (RFC 0004 §8;
 * materialization.rs). The item target is the post-order rank of
 * the emitted value (materialization.rs): for the XML profile the
 * rank runs over value-only entities in close order (dict keys are
 * excluded), and for the binary profile it is the object-table index. */
private fun buildProvenance(
    items: List<InputItem>,
    document: Document,
    limits: MaterializationLimits,
): MaterializationProvenanceMap {
    val valueIndices = document.entities.indices.filter {
        (document.entities[it] as? Entity.Value)?.entity?.isKey == false
    }
    val entries = ArrayList<MaterializationProvenanceEntry>()
    for (item in items) {
        val index = valueIndices.getOrNull(item.target) ?: continue
        val entity = (document.entities[index] as Entity.Value).entity
        entries.add(
            MaterializationProvenanceEntry(
                input = MaterializationInputLocation.Value(item.path),
                outputs = listOf(
                    MaterializedOrigin(
                        snapshot = document.snapshotIdentity,
                        node = document.nodeRef(index.toLong(), consema.document.NodeRole.PlistValue),
                        span = entity.span,
                        relation = MaterializationRelation.Direct,
                    ),
                ),
            ),
        )
    }
    return MaterializationProvenanceMap.new(entries, document.snapshotIdentity, limits)
}

/** The sign bit of one double (true for -0.0, -inf, and negatives). */
private fun negativeSign(value: Double): Boolean =
    java.lang.Double.doubleToRawLongBits(value) < 0

/** Exact signed 64-bit conversion of one portable integer; null when the magnitude exceeds the range. */
private fun bigIntegerToLong(value: java.math.BigInteger): Long? =
    try {
        value.toLong()
    } catch (e: NumberFormatException) {
        null
    }

/** Truncation toward zero (the fractional-date truncation policy). */
private fun truncTowardZero(value: Double): Double =
    if (value >= 0.0) java.lang.Math.floor(value) else java.lang.Math.ceil(value)
