// Canonical `xml.safe-canonical-document@1` materialization (RFC 0012 §10).
//
// Data authority:
//   - RFC 0012 §10 (https://github.com/consema/consema/blob/main/docs/rfcs/0012-xml-1.0-safe-profile-v1.md:350-373):
//     the canonical style consumes one fully validated `xml.element-tree@1`
//     value and creates a new `xml.1.0-safe@1` Document; it is not W3C
//     Canonical XML; the style deterministically chooses declaration
//     spelling, double-quoted attributes, generated namespace prefixes,
//     first-use namespace declaration placement, empty-element spelling,
//     reference spelling, and the requested LF/CRLF final newline; UTF-8,
//     UTF-16LE, and UTF-16BE output are supported under the source rules;
//     UTF-16 output always carries its BOM; the complete tree is validated
//     before generation, the exact generated bytes are reparsed under the
//     promised Profile and encoding, and the reparsed native tree is
//     compared to the promised input semantics; failure returns no target
//     Document and no partial output bytes.
//   - conformance/vectors/xml-1-0-safe-v1.json cases xml.materialization.*
//     pin the render bytes and the `"invalid-record"` failure spelling.
//   - https://github.com/consema/consema-rs/blob/main/consema-xml/src/materialization.rs is the byte-arbitration
//     authority: entry (materialization.rs:36-88), request validation
//     (materialization.rs:90-107), reparse limits (materialization.rs:
//     109-140), encoding (materialization.rs:142-172), record validation
//     (materialization.rs:174-500), the prefix table (materialization.rs:
//     502-526), the writer (materialization.rs:565-900), and the closure
//     verification (materialization.rs:902-1100).
//   - RFC 0004 §3/§7 (https://github.com/consema/consema/blob/main/docs/rfcs/0004-materialization-conversion-and-structural-edit-v1.md:57-84, 171-186) pins the common
//     MaterializationRequest and the completion algebra; the Kotlin common
//     contracts live in consema.document (Materialization.kt).
//
// The failure spellings used by the vectors are the stable
// `materialization_failure_code` mapping of the conformance runner
// (https://github.com/consema/consema-rs/blob/main/consema-conformance/src/xml_v1.rs:855-871): `"invalid-record"`
// for InvalidRequest, plus unsupported-profile / unsupported-style /
// unsupported-encoding / unsupported-newline / unrepresentable /
// resource-limit / formation-failed.
//
// Kotlin-idiomatic design: the writer is a byte buffer with checked growth;
// the input record is an immutable validated mirror of `xml.element-tree@1`;
// closure verification walks the input and the reparsed document in
// lockstep and pairs every recorded input location with its exact output
// origin (materialization.rs:902-1100).

package consema.xml

import consema.core.PortableValue
import consema.core.PvArray
import consema.core.PvBoolean
import consema.core.PvNull
import consema.core.PvObject
import consema.core.PvString
import consema.core.ValuePath
import consema.core.ValuePathSegment
import consema.core.AssociationLocation
import consema.core.AssociationRole
import consema.document.CompleteMaterialization
import consema.document.FailedMaterializationAttempt
import consema.document.MaterializationException
import consema.document.MaterializationFailureKind
import consema.document.MaterializationFidelity
import consema.document.MaterializationInputLocation
import consema.document.MaterializationLimits
import consema.document.MaterializationProvenanceEntry
import consema.document.MaterializationProvenanceMap
import consema.document.MaterializationRelation
import consema.document.MaterializationReport
import consema.document.MaterializationRequest
import consema.document.MaterializationResult
import consema.document.MaterializedOrigin
import consema.document.NewlinePolicy
import consema.document.NodeRef
import consema.document.NodeRole
import consema.document.ParseLimits
import consema.document.SourceEncoding
import consema.document.Span
import java.nio.charset.StandardCharsets

/**
 * Materializes one `xml.element-tree@1` record into a new canonical
 * `xml.1.0-safe@1` document (materialization.rs:36-88). A failure returns no
 * Document, no partial bytes, and no provenance that can be mistaken for a
 * result (RFC 0004 §3).
 */
fun materialize(
    value: PortableValue,
    request: MaterializationRequest,
): MaterializationResult<Document> {
    val analyzed = ArrayList<ValuePath>()
    return try {
        val complete = materializeComplete(value, request, analyzed)
        MaterializationResult.Complete(complete)
    } catch (e: MaterializationException) {
        MaterializationResult.Failed(
            FailedMaterializationAttempt(
                failure = e,
                report = MaterializationReport.new(emptyList(), request.limits),
                analyzedInputPaths = analyzed,
            ),
        )
    }
}

private fun materializeComplete(
    value: PortableValue,
    request: MaterializationRequest,
    analyzed: MutableList<ValuePath>,
): CompleteMaterialization<Document> {
    validateRequest(request)
    val input = Record.validate(value, analyzed)
    val writer = Writer(request.limits)
    writer.emitDocument(input, request)
    val text = writer.output.toByteArray()
    val bytes = encodeText(text, request.encoding, request.limits.maxOutputBytes)
    val document = try {
        parse(
            bytes,
            XmlProfile.SafeV1,
            XmlEncodingSelection.ProfileDefault,
            parseLimits(request.limits),
        )
    } catch (e: XmlFormationException) {
        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
    }
    if (document.formationStatus != consema.document.FormationStatus.Complete) {
        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
    }
    val provenance = verifyClosure(input, document, writer.items, request.limits)
    return CompleteMaterialization(
        document = document,
        fidelity = MaterializationFidelity.Exact,
        report = MaterializationReport.new(emptyList(), request.limits),
        provenance = provenance,
    )
}

private fun validateRequest(request: MaterializationRequest) {
    if (request.targetProfile.id != "xml.1.0-safe" || request.targetProfile.version != 1) {
        throw MaterializationException(MaterializationFailureKind.UNSUPPORTED_PROFILE)
    }
    if (request.style.id != "xml.safe-canonical-document" || request.style.version != 1) {
        throw MaterializationException(MaterializationFailureKind.UNSUPPORTED_STYLE)
    }
    if (request.encoding !== SourceEncoding.Utf8 &&
        request.encoding !== SourceEncoding.Utf16Le &&
        request.encoding !== SourceEncoding.Utf16Be
    ) {
        throw MaterializationException(MaterializationFailureKind.UNSUPPORTED_ENCODING)
    }
    if (request.newline != NewlinePolicy.Lf && request.newline != NewlinePolicy.CrLf) {
        throw MaterializationException(MaterializationFailureKind.UNSUPPORTED_NEWLINE)
    }
}

/** Reparse limits derived from the materialization limits
 * (materialization.rs:109-140). */
private fun parseLimits(limits: MaterializationLimits): XmlParseLimits =
    XmlParseLimits(
        common = ParseLimits(
            maxSourceBytes = limits.maxOutputBytes,
            maxNestingDepth = limits.maxDepth,
            maxTokenCount = limits.maxOutputBytes,
            maxNodeCount = limits.maxInputNodes,
            maxDiagnostics = limits.maxReportEntries,
        ),
        maxDecodedUtf8Bytes = saturatedMultiply(limits.maxOutputBytes, 3),
        maxDecodedScalars = limits.maxOutputBytes,
        maxElementCount = limits.maxInputNodes,
        maxAttributeCount = limits.maxInputNodes,
        maxNamespaceDeclarationCount = limits.maxInputNodes,
        maxMixedContentItems = limits.maxInputNodes,
        maxQnameLength = limits.maxOutputBytes,
        maxNamespaceUriLength = limits.maxOutputBytes,
        maxAttributeValueLength = limits.maxOutputBytes,
        maxCommentLength = limits.maxOutputBytes,
        maxPiLength = limits.maxOutputBytes,
        maxCdataLength = limits.maxOutputBytes,
        maxTextLength = limits.maxOutputBytes,
        maxDtdBytes = limits.maxOutputBytes,
        maxEntityDeclarations = limits.maxInputNodes,
        maxEntityReferences = limits.maxInputNodes,
        maxEntityExpansionDepth = limits.maxDepth,
        maxExpandedEntityBytes = limits.maxOutputBytes,
        maxExpandedEntityScalars = limits.maxOutputBytes,
        maxEntityAmplificationRatio = Long.MAX_VALUE,
        maxRecoveryRegions = limits.maxReportEntries,
    )

private fun saturatedMultiply(left: Int, right: Int): Int =
    if (left > Int.MAX_VALUE / right) Int.MAX_VALUE else left * right

/** Encodes canonical UTF-8 text into the requested output encoding
 * (materialization.rs:142-172). */
private fun encodeText(
    text: ByteArray,
    encoding: SourceEncoding,
    maxOutputBytes: Int,
): ByteArray {
    val output = java.io.ByteArrayOutputStream()
    when (encoding) {
        SourceEncoding.Utf8 -> output.write(text)
        SourceEncoding.Utf16Le, SourceEncoding.Utf16Be -> {
            // The writer only ever emits valid UTF-8.
            val decoded = String(text, StandardCharsets.UTF_8)
            val littleEndian = encoding === SourceEncoding.Utf16Le
            output.write(if (littleEndian) byteArrayOf(0xFF.toByte(), 0xFE.toByte()) else byteArrayOf(0xFE.toByte(), 0xFF.toByte()))
            for (unit in decoded) {
                val high = (unit.code ushr 8) and 0xff
                val low = unit.code and 0xff
                output.write(if (littleEndian) byteArrayOf(low.toByte(), high.toByte()) else byteArrayOf(high.toByte(), low.toByte()))
            }
        }
        else -> throw MaterializationException(MaterializationFailureKind.UNSUPPORTED_ENCODING)
    }
    val bytes = output.toByteArray()
    if (bytes.size > maxOutputBytes) {
        throw MaterializationException(
            MaterializationFailureKind.RESOURCE_LIMIT,
            name = "output-bytes",
        )
    }
    return bytes
}

// ---------------------------------------------------------------------------
// Validated input record
// ---------------------------------------------------------------------------

/** Validated input record mirroring `xml.element-tree@1`
 * (materialization.rs:174-237). */
private class XmlRecord(
    val declaration: DeclarationRecord?,
    val entities: List<EntityRecord>,
    val root: XmlElementRecord,
)

private class DeclarationRecord(
    val version: String,
    val encoding: String?,
    val standalone: Boolean?,
    val path: ValuePath,
)

private class EntityRecord(
    val name: String,
    val replacement: String,
    val path: ValuePath,
)

private class XmlElementRecord(
    val namespace: String?,
    val local: String,
    val namespaces: List<Pair<String?, String>>,
    val attributes: List<AttributeRecord>,
    val content: List<ContentRecord>,
    val path: ValuePath,
)

private class AttributeRecord(
    val namespace: String?,
    val local: String,
    val value: String,
    val path: ValuePath,
)

private sealed class ContentRecord {
    abstract val path: ValuePath

    data class Element(val element: XmlElementRecord, override val path: ValuePath) : ContentRecord()

    data class Text(
        val fragments: List<FragmentRecord>,
        override val path: ValuePath,
    ) : ContentRecord()

    data class Cdata(val text: String, override val path: ValuePath) : ContentRecord()

    data class Comment(val text: String, override val path: ValuePath) : ContentRecord()

    data class ProcessingInstruction(
        val target: String,
        val content: String?,
        override val path: ValuePath,
    ) : ContentRecord()
}

private sealed class FragmentRecord {
    data class Literal(val text: String) : FragmentRecord()
    data class CharacterReference(val resolved: Char) : FragmentRecord()
    data class PredefinedEntity(val name: String, val resolved: String) : FragmentRecord()
    data class GeneralEntity(val name: String, val resolved: String) : FragmentRecord()
}

/** Strict record validation (materialization.rs:238-500). */
private object Record {
    fun validate(value: PortableValue, analyzed: MutableList<ValuePath>): XmlRecord {
        analyzed.add(ValuePath.root())
        val rootPath = ValuePath.root().child(ValuePathSegment.ObjectValue("root"))
        val record = expectStringField(value, "record", ValuePath.root())
        if (record != "xml.element-tree@1") {
            throw MaterializationException(
                MaterializationFailureKind.INVALID_REQUEST,
                reason = "input record is not xml.element-tree@1",
            )
        }
        val rootValue = expectField(value, "root", rootPath)
        val declaration = when (val pair = expectOptionalObjectField(value, "declaration")) {
            null -> null
            else -> {
                val (declarationValue, path) = pair
                val version = expectStringField(declarationValue, "version", path)
                if (version != "1.0") {
                    throw MaterializationException(
                        MaterializationFailureKind.UNREPRESENTABLE,
                        path = path.child(ValuePathSegment.ObjectValue("version")),
                        valueKind = consema.core.Kind.String,
                    )
                }
                val encoding = expectOptionalStringField(declarationValue, "encoding", path)
                val standalone = expectOptionalBooleanField(declarationValue, "standalone", path)
                DeclarationRecord(version, encoding, standalone, path)
            }
        }
        val entities = when (val pair = expectOptionalSequenceField(value, "entities")) {
            null -> emptyList()
            else -> {
                val (entityList, path) = pair
                entityList.mapIndexed { index, entity ->
                    val entityPath = path.child(ValuePathSegment.SequenceElement(index.toLong()))
                    val name = expectStringField(entity, "name", entityPath)
                    val replacement = expectStringField(entity, "replacement", entityPath)
                    if (replacement.contains('<')) {
                        throw MaterializationException(
                            MaterializationFailureKind.UNREPRESENTABLE,
                            path = entityPath.child(ValuePathSegment.ObjectValue("replacement")),
                            valueKind = consema.core.Kind.String,
                        )
                    }
                    EntityRecord(name, replacement, entityPath)
                }
            }
        }
        val root = ElementRecord.validate(rootValue, rootPath, analyzed)
        return XmlRecord(declaration, entities, root)
    }

    fun expectStringField(value: PortableValue, name: String, path: ValuePath): String {
        val objectValue = asObject(value, path)
        val field = objectValue.get(name)
            ?: throw MaterializationException(
                MaterializationFailureKind.INVALID_REQUEST,
                reason = "missing record field",
            )
        return (field as? PvString)?.value
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path.child(ValuePathSegment.ObjectValue(name)),
                valueKind = field.kind,
            )
    }

    /** Fetches one object field of any kind (the Rust
     * expect_object_field, materialization.rs:1239-1256). */
    fun expectField(value: PortableValue, name: String, path: ValuePath): PortableValue {
        val objectValue = asObject(value, path)
        return objectValue.get(name)
            ?: throw MaterializationException(
                MaterializationFailureKind.INVALID_REQUEST,
                reason = "missing record field",
            )
    }

    /** Fetches one object field whose value must be an Object. */
    fun expectObjectField(value: PortableValue, name: String, path: ValuePath): PvObject {
        val field = expectField(value, name, path)
        return field as? PvObject
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path.child(ValuePathSegment.ObjectValue(name)),
                valueKind = field.kind,
            )
    }

    /** Fetches an optional object field from the record root
     * (materialization.rs:1258-1266). */
    fun expectOptionalObjectField(
        value: PortableValue,
        name: String,
    ): Pair<PortableValue, ValuePath>? {
        val objectValue = asObject(value, ValuePath.root())
        val field = objectValue.get(name) ?: return null
        val path = ValuePath.root().child(ValuePathSegment.ObjectValue(name))
        return field to path
    }

    fun expectOptionalStringField(
        value: PortableValue,
        name: String,
        path: ValuePath,
    ): String? {
        val objectValue = value as? PvObject ?: return null
        val field = objectValue.get(name) ?: return null
        if (field is PvNull) {
            return null
        }
        return (field as? PvString)?.value
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path.child(ValuePathSegment.ObjectValue(name)),
                valueKind = field.kind,
            )
    }

    fun expectOptionalBooleanField(
        value: PortableValue,
        name: String,
        path: ValuePath,
    ): Boolean? {
        val objectValue = value as? PvObject ?: return null
        val field = objectValue.get(name) ?: return null
        if (field is PvNull) {
            return null
        }
        return (field as? PvBoolean)?.value
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path.child(ValuePathSegment.ObjectValue(name)),
                valueKind = field.kind,
            )
    }

    fun expectOptionalSequenceField(
        value: PortableValue,
        name: String,
    ): Pair<List<PortableValue>, ValuePath>? {
        val objectValue = value as? PvObject ?: return null
        val field = objectValue.get(name) ?: return null
        val path = ValuePath.root().child(ValuePathSegment.ObjectValue(name))
        val sequence = (field as? PvArray)?.items()
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path,
                valueKind = field.kind,
            )
        return sequence to path
    }

    private fun asObject(value: PortableValue, path: ValuePath): PvObject =
        value as? PvObject
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path,
                valueKind = value.kind,
            )
}

private object ElementRecord {
    fun validate(
        value: PortableValue,
        path: ValuePath,
        analyzed: MutableList<ValuePath>,
    ): XmlElementRecord {
        analyzed.add(path)
        val (namespace, local) = expectExpandedName(value, path)
        val namespaces = when (val pair = Record.expectOptionalSequenceField(value, "namespaces")) {
            null -> emptyList()
            else -> {
                val (bindings, bindingsPath) = pair
                bindings.mapIndexed { index, binding ->
                    val bindingPath =
                        bindingsPath.child(ValuePathSegment.SequenceElement(index.toLong()))
                    val prefix = Record.expectOptionalStringField(binding, "prefix", bindingPath)
                    val uri = Record.expectStringField(binding, "uri", bindingPath)
                    prefix to uri
                }
            }
        }
        val attributes = when (val pair = Record.expectOptionalSequenceField(value, "attributes")) {
            null -> emptyList()
            else -> {
                val (attributeList, attributesPath) = pair
                attributeList.mapIndexed { index, attribute ->
                    val attributePath =
                        attributesPath.child(ValuePathSegment.SequenceElement(index.toLong()))
                    val (attrNamespace, attrLocal) = expectExpandedName(attribute, attributePath)
                    val valueText = Record.expectStringField(attribute, "value", attributePath)
                    AttributeRecord(attrNamespace, attrLocal, valueText, attributePath)
                }
            }
        }
        val content = when (val pair = Record.expectOptionalSequenceField(value, "content")) {
            null -> emptyList()
            else -> {
                val (contentList, contentPath) = pair
                contentList.mapIndexed { index, item ->
                    val itemPath =
                        contentPath.child(ValuePathSegment.SequenceElement(index.toLong()))
                    val itemObject = asObject(item, itemPath)
                    if (itemObject.get("expanded-name") != null) {
                        ContentRecord.Element(
                            validate(item, itemPath, analyzed),
                            itemPath,
                        )
                    } else {
                        when (val kind = Record.expectStringField(item, "kind", itemPath)) {
                            "text" -> {
                                val fragmentsPath = itemPath
                                    .child(ValuePathSegment.ObjectValue("fragments"))
                                val fragmentsValue =
                                    Record.expectField(item, "fragments", fragmentsPath)
                                val fragmentsSequence = (fragmentsValue as? PvArray)?.items()
                                    ?: throw MaterializationException(
                                        MaterializationFailureKind.UNREPRESENTABLE,
                                        path = fragmentsPath,
                                        valueKind = fragmentsValue.kind,
                                    )
                                val fragments = fragmentsSequence.mapIndexed { fragmentIndex, fragment ->
                                    val fragmentPath = fragmentsPath
                                        .child(ValuePathSegment.SequenceElement(fragmentIndex.toLong()))
                                    when (val fragmentKind =
                                        Record.expectStringField(fragment, "kind", fragmentPath)
                                    ) {
                                        "literal" -> FragmentRecord.Literal(
                                            Record.expectStringField(fragment, "text", fragmentPath),
                                        )
                                        "character-reference" -> {
                                            val resolved =
                                                Record.expectStringField(fragment, "resolved", fragmentPath)
                                            if (resolved.length != 1) {
                                                throw MaterializationException(
                                                    MaterializationFailureKind.UNREPRESENTABLE,
                                                    path = fragmentPath,
                                                    valueKind = consema.core.Kind.String,
                                                )
                                            }
                                            FragmentRecord.CharacterReference(resolved[0])
                                        }
                                        "predefined-entity" -> FragmentRecord.PredefinedEntity(
                                            Record.expectStringField(fragment, "name", fragmentPath),
                                            Record.expectStringField(fragment, "resolved", fragmentPath),
                                        )
                                        "general-entity" -> FragmentRecord.GeneralEntity(
                                            Record.expectStringField(fragment, "name", fragmentPath),
                                            Record.expectStringField(fragment, "resolved", fragmentPath),
                                        )
                                        else -> throw MaterializationException(
                                            MaterializationFailureKind.UNREPRESENTABLE,
                                            path = fragmentPath,
                                            valueKind = fragment.kind,
                                        )
                                    }
                                }
                                ContentRecord.Text(fragments, itemPath)
                            }
                            "cdata" -> ContentRecord.Cdata(
                                Record.expectStringField(item, "text", itemPath),
                                itemPath,
                            )
                            "comment" -> ContentRecord.Comment(
                                Record.expectStringField(item, "text", itemPath),
                                itemPath,
                            )
                            "processing-instruction" -> ContentRecord.ProcessingInstruction(
                                Record.expectStringField(item, "target", itemPath),
                                Record.expectOptionalStringField(itemObject, "content", itemPath),
                                itemPath,
                            )
                            else -> throw MaterializationException(
                                MaterializationFailureKind.UNREPRESENTABLE,
                                path = itemPath,
                                valueKind = item.kind,
                            )
                        }
                    }
                }
            }
        }
        val names = HashSet<Pair<String?, String>>()
        for (attribute in attributes) {
            val key = attribute.namespace to attribute.local
            if (!names.add(key)) {
                throw MaterializationException(
                    MaterializationFailureKind.INVALID_REQUEST,
                    reason = "duplicate expanded attribute in input record",
                )
            }
        }
        return XmlElementRecord(namespace, local, namespaces, attributes, content, path)
    }

    fun expectExpandedName(value: PortableValue, path: ValuePath): Pair<String?, String> {
        val name = Record.expectObjectField(value, "expanded-name", path)
        val namePath = path.child(ValuePathSegment.ObjectValue("expanded-name"))
        val namespace = Record.expectOptionalStringField(name, "namespace", namePath)
        val local = Record.expectStringField(name, "local", namePath)
        return namespace to local
    }

    private fun asObject(value: PortableValue, path: ValuePath): PvObject =
        value as? PvObject
            ?: throw MaterializationException(
                MaterializationFailureKind.UNREPRESENTABLE,
                path = path,
                valueKind = value.kind,
            )
}

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

/** Deterministic generated-prefix assignment by first-encounter order
 * (materialization.rs:502-526). */
private class PrefixTable {
    private val entries = HashMap<String, String>()
    private var next = 0

    fun prefixFor(namespace: String, default: String?): String {
        if (namespace == default) {
            return ""
        }
        if (namespace == XML_NAMESPACE_URI) {
            return "xml"
        }
        entries[namespace]?.let { return it }
        next += 1
        val prefix = "ns$next"
        entries[namespace] = prefix
        return prefix
    }
}

/** One input location recorded during generation, paired by order with the
 * reparsed document during closure verification (materialization.rs:
 * 528-563). */
private sealed class InputItem {
    abstract val path: ValuePath

    data class Declaration(override val path: ValuePath) : InputItem()
    data class Entity(override val path: ValuePath) : InputItem()
    data class Element(override val path: ValuePath) : InputItem()
    data class NamespaceBinding(override val path: ValuePath) : InputItem()
    data class Attribute(override val path: ValuePath) : InputItem()
    data class Text(override val path: ValuePath) : InputItem()
    data class Fragment(override val path: ValuePath) : InputItem()
    data class Cdata(override val path: ValuePath) : InputItem()
    data class Comment(override val path: ValuePath) : InputItem()
    data class ProcessingInstruction(override val path: ValuePath) : InputItem()

    fun location(): MaterializationInputLocation =
        when (this) {
            is NamespaceBinding -> MaterializationInputLocation.Association(
                AssociationLocation(path, 0L, AssociationRole.ObjectEntry),
            )
            else -> MaterializationInputLocation.Value(path)
        }
}

/** The deterministic canonical writer (materialization.rs:565-900). */
private class Writer(private val limits: MaterializationLimits) {
    val output = java.io.ByteArrayOutputStream()
    val items = ArrayList<InputItem>()
    private var inputNodes = 0
    private val prefixes = PrefixTable()
    /** In-scope bindings as `(prefix, uri)` with null the default
     * namespace; restored by truncation when an element exits. */
    private val scope = ArrayList<Pair<String?, String>>()

    private fun step() {
        inputNodes += 1
        if (inputNodes > limits.maxInputNodes) {
            throw MaterializationException(
                MaterializationFailureKind.RESOURCE_LIMIT,
                name = "input-nodes",
            )
        }
    }

    private fun push(bytes: ByteArray) {
        output.write(bytes)
        if (output.size() > limits.maxOutputBytes) {
            throw MaterializationException(
                MaterializationFailureKind.RESOURCE_LIMIT,
                name = "output-bytes",
            )
        }
    }

    private fun push(text: String) {
        push(text.toByteArray(StandardCharsets.UTF_8))
    }

    /** Spelling prefix for one expanded namespace, using the current scope
     * (materialization.rs:596-621). `""` means unprefixed; null means the
     * URI is not bound in scope and a declaration must be generated. */
    private fun spellingPrefix(uri: String?): String? =
        when {
            uri == null -> ""
            uri == XML_NAMESPACE_URI -> "xml"
            else -> {
                if (scope.asReversed().any { it.first == null && it.second == uri }) {
                    ""
                } else {
                    scope.asReversed()
                        .firstOrNull { it.first != null && it.second == uri }
                        ?.first
                }
            }
        }

    private fun pushEscapedText(text: String) {
        var rest = text
        while (true) {
            val at = rest.indexOfFirst { it == '&' || it == '<' }
            if (at < 0) {
                push(rest)
                return
            }
            push(rest.substring(0, at))
            when (rest[at]) {
                '&' -> push("&amp;")
                else -> push("&lt;")
            }
            rest = rest.substring(at + 1)
        }
    }

    private fun pushEscapedAttribute(text: String) {
        var rest = text
        while (true) {
            val at = rest.indexOfFirst { it == '&' || it == '<' || it == '"' }
            if (at < 0) {
                push(rest)
                return
            }
            push(rest.substring(0, at))
            when (rest[at]) {
                '&' -> push("&amp;")
                '<' -> push("&lt;")
                else -> push("&quot;")
            }
            rest = rest.substring(at + 1)
        }
    }

    fun emitDocument(input: XmlRecord, request: MaterializationRequest) {
        step()
        input.declaration?.let { declaration ->
            items.add(InputItem.Declaration(declaration.path))
            push("<?xml version=\"")
            pushEscapedAttribute(declaration.version)
            push("\"")
            val declaredEncoding = declaration.encoding ?: run {
                if (request.encoding === SourceEncoding.Utf16Le ||
                    request.encoding === SourceEncoding.Utf16Be
                ) {
                    "UTF-16"
                } else {
                    null
                }
            }
            if (declaredEncoding != null) {
                push(" encoding=\"")
                pushEscapedAttribute(declaredEncoding)
                push("\"")
            }
            if (declaration.standalone != null) {
                push(if (declaration.standalone) " standalone=\"yes\"" else " standalone=\"no\"")
            }
            push("?>")
        }
        if (input.entities.isNotEmpty()) {
            push("<!DOCTYPE ")
            val doctypeName = when (val prefix = spellingPrefix(input.root.namespace)) {
                "" -> input.root.local
                null -> {
                    // An unbound root namespace cannot be named in the
                    // DOCTYPE without a declaration; fail honestly.
                    throw MaterializationException(
                        MaterializationFailureKind.UNREPRESENTABLE,
                        path = input.root.path,
                        valueKind = consema.core.Kind.Object,
                    )
                }
                else -> "$prefix:${input.root.local}"
            }
            push(doctypeName)
            push(" [")
            for (entity in input.entities) {
                items.add(InputItem.Entity(entity.path))
                push("<!ENTITY ")
                push(entity.name)
                push(" \"")
                pushEscapedAttribute(entity.replacement)
                push("\">")
            }
            push("]>")
        }
        emitElement(input.root, 0)
        push(request.newline.bytes())
    }

    private fun emitElement(element: XmlElementRecord, depth: Int) {
        step()
        if (depth > limits.maxDepth) {
            throw MaterializationException(
                MaterializationFailureKind.RESOURCE_LIMIT,
                name = "input-depth",
            )
        }
        items.add(InputItem.Element(element.path))
        val scopeLen = scope.size
        // The record's namespace declarations are reproduced verbatim in
        // order; the spelling of names follows the resulting scope.
        for ((prefix, uri) in element.namespaces) {
            scope.add(prefix to uri)
        }
        val elementPrefix = when (val prefix = spellingPrefix(element.namespace)) {
            null -> {
                // Unbound URI in a hand-built record: declare a generated
                // default namespace on this element.
                val uri = element.namespace ?: XML_NAMESPACE_URI
                if (uri == XML_NAMESPACE_URI) {
                    "xml"
                } else {
                    push("<")
                    push(element.local)
                    push(" xmlns=\"")
                    pushEscapedAttribute(uri)
                    push("\"")
                    scope.add(null to uri)
                    items.add(InputItem.NamespaceBinding(element.path))
                    ""
                }
            }
            else -> prefix
        }
        push("<")
        if (elementPrefix.isEmpty()) {
            push(element.local)
        } else {
            push("$elementPrefix:${element.local}")
        }
        for ((prefix, uri) in element.namespaces) {
            items.add(InputItem.NamespaceBinding(element.path))
            if (prefix != null) {
                push(" xmlns:$prefix=\"")
                pushEscapedAttribute(uri)
                push("\"")
            } else {
                push(" xmlns=\"")
                pushEscapedAttribute(uri)
                push("\"")
            }
        }
        for (attribute in element.attributes) {
            items.add(InputItem.Attribute(attribute.path))
            val attributePrefix = when (val prefix = spellingPrefix(attribute.namespace)) {
                null -> {
                    // Unbound attribute namespace: declare a generated
                    // prefix on this element.
                    val uri = attribute.namespace ?: XML_NAMESPACE_URI
                    val generated = prefixes.prefixFor(uri, null)
                    push(" xmlns:$generated=\"")
                    pushEscapedAttribute(uri)
                    push("\"")
                    scope.add(generated to uri)
                    items.add(InputItem.NamespaceBinding(element.path))
                    generated
                }
                else -> prefix
            }
            push(" ")
            if (attributePrefix.isEmpty()) {
                push(attribute.local)
            } else {
                push("$attributePrefix:${attribute.local}")
            }
            push("=\"")
            pushEscapedAttribute(attribute.value)
            push("\"")
        }
        if (element.content.isEmpty()) {
            push("/>")
            restoreScope(scopeLen)
            return
        }
        push(">")
        for (item in element.content) {
            when (item) {
                is ContentRecord.Element -> emitElement(item.element, depth + 1)
                is ContentRecord.Text -> {
                    items.add(InputItem.Text(item.path))
                    for (fragment in item.fragments) {
                        items.add(InputItem.Fragment(item.path))
                        when (fragment) {
                            is FragmentRecord.Literal -> pushEscapedText(fragment.text)
                            is FragmentRecord.CharacterReference ->
                                push("&#${fragment.resolved.code};")

                            is FragmentRecord.PredefinedEntity,
                            is FragmentRecord.GeneralEntity,
                            -> {
                                val entityName = when (fragment) {
                                    is FragmentRecord.PredefinedEntity -> fragment.name
                                    else -> (fragment as FragmentRecord.GeneralEntity).name
                                }
                                push("&$entityName;")
                            }
                        }
                    }
                }
                is ContentRecord.Cdata -> {
                    items.add(InputItem.Cdata(item.path))
                    if (item.text.contains("]]>")) {
                        throw MaterializationException(
                            MaterializationFailureKind.UNREPRESENTABLE,
                            path = item.path,
                            valueKind = consema.core.Kind.String,
                        )
                    }
                    push("<![CDATA[")
                    push(item.text)
                    push("]]>")
                }
                is ContentRecord.Comment -> {
                    items.add(InputItem.Comment(item.path))
                    if (item.text.contains("--") || item.text.endsWith('-')) {
                        throw MaterializationException(
                            MaterializationFailureKind.UNREPRESENTABLE,
                            path = item.path,
                            valueKind = consema.core.Kind.String,
                        )
                    }
                    push("<!--")
                    push(item.text)
                    push("-->")
                }
                is ContentRecord.ProcessingInstruction -> {
                    items.add(InputItem.ProcessingInstruction(item.path))
                    if (item.target.equals("xml", ignoreCase = true) ||
                        item.content?.contains("?>") == true
                    ) {
                        throw MaterializationException(
                            MaterializationFailureKind.UNREPRESENTABLE,
                            path = item.path,
                            valueKind = consema.core.Kind.String,
                        )
                    }
                    push("<?")
                    push(item.target)
                    item.content?.let { content ->
                        push(" ")
                        push(content)
                    }
                    push("?>")
                }
            }
        }
        push("</")
        if (elementPrefix.isEmpty()) {
            push(element.local)
        } else {
            push("$elementPrefix:${element.local}")
        }
        push(">")
        restoreScope(scopeLen)
    }

    /** Restores the in-scope bindings to the length recorded at element
     * entry (the truncation of materialization.rs:840-845). */
    private fun restoreScope(scopeLen: Int) {
        while (scope.size > scopeLen) {
            scope.removeAt(scope.size - 1)
        }
    }
}

// ---------------------------------------------------------------------------
// Closure verification
// ---------------------------------------------------------------------------

/** One matched output origin in the reparsed document (materialization.rs:
 * 902-907). */
private class OutputItem(
    val node: NodeRef,
    val span: Span,
    val relation: MaterializationRelation,
)

/**
 * Walks the input record and the reparsed document in lockstep, compares
 * the promised semantics, and pairs every recorded input location with its
 * exact output origin. Any mismatch fails the whole materialization
 * (materialization.rs:909-1100).
 */
private fun verifyClosure(
    input: XmlRecord,
    document: Document,
    items: List<InputItem>,
    limits: MaterializationLimits,
): MaterializationProvenanceMap {
    val outputs = ArrayList<OutputItem>()
    val root = document.root() ?: throw MaterializationException(
        MaterializationFailureKind.FORMATION_FAILED,
    )
    // Declaration closure.
    when {
        input.declaration == null && document.declaration() == null -> {}
        input.declaration != null && document.declaration() != null -> {
            val declared = input.declaration!!
            val reparsed = document.declaration()!!
            if (reparsed.version != declared.version ||
                reparsed.standalone?.second != declared.standalone
            ) {
                throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
            }
        }
        else -> throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
    }
    // Entity closure.
    val reparsedDoctype = document.doctype()
    if (reparsedDoctype != null) {
        if (reparsedDoctype.entities.size != input.entities.size ||
            reparsedDoctype.entities.zip(input.entities).any { (reparsed, declared) ->
                reparsed.name != declared.name || reparsed.replacement != declared.replacement
            }
        ) {
            throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
        }
    } else if (input.entities.isNotEmpty()) {
        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
    }
    // Declaration and entity outputs precede the tree walk, matching the
    // generation order of their input items.
    if (input.declaration != null) {
        val declared = document.declaration() ?: throw MaterializationException(
            MaterializationFailureKind.FORMATION_FAILED,
        )
        outputs.add(
            OutputItem(
                document.authority.nodeRef(1, NodeRole.XmlDeclaration),
                declared.span,
                MaterializationRelation.Direct,
            ),
        )
    }
    reparsedDoctype?.let { doctype ->
        for (entity in doctype.entities) {
            outputs.add(
                OutputItem(
                    document.authority.nodeRef(2, NodeRole.XmlDoctype),
                    entity.span,
                    MaterializationRelation.Direct,
                ),
            )
        }
    }
    val context = ClosureContext(document, outputs, limits)
    context.element(input.root, root)
    // Pair input items with outputs by traversal order; adjacent items with
    // the same input location share one provenance entry.
    if (outputs.size != items.size) {
        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
    }
    val entries = ArrayList<MaterializationProvenanceEntry>()
    for ((item, output) in items.zip(outputs)) {
        val location = item.location()
        val origin = MaterializedOrigin(
            snapshot = document.snapshotIdentity,
            node = output.node,
            span = output.span,
            relation = output.relation,
        )
        val previous = entries.lastOrNull()
        if (previous != null && previous.input == location) {
            entries[entries.size - 1] = MaterializationProvenanceEntry(
                location,
                previous.outputs + origin,
            )
        } else {
            entries.add(MaterializationProvenanceEntry(location, listOf(origin)))
        }
    }
    return MaterializationProvenanceMap.new(entries, document.snapshotIdentity, limits)
}

/** One element closure walk over the reparsed document
 * (materialization.rs:1016-1210). */
private class ClosureContext(
    private val document: Document,
    private val outputs: MutableList<OutputItem>,
    private val limits: MaterializationLimits,
) {
    private fun push(node: NodeRef, span: Span, relation: MaterializationRelation) {
        if (outputs.size >= limits.maxProvenanceEntries) {
            throw MaterializationException(
                MaterializationFailureKind.RESOURCE_LIMIT,
                name = "provenance-entries",
            )
        }
        outputs.add(OutputItem(node, span, relation))
    }

    fun element(input: XmlElementRecord, reparsed: XmlElement) {
        val data = document.elementData(reparsed.index)
        // The element output precedes the namespace and attribute outputs,
        // matching the generation order of the writer's input items.
        push(reparsed.nodeRef(), data.span, MaterializationRelation.Direct)
        val expanded = data.expanded
            ?: throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
        val nameMatches = when {
            input.namespace != null && expanded.namespace != null ->
                input.namespace == expanded.namespace

            input.namespace == null && expanded.namespace == null -> true
            else -> false
        }
        if (!nameMatches || expanded.local != input.local) {
            throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
        }
        for (binding in data.namespaces) {
            push(
                document.authority.nodeRef(binding.ordinal, NodeRole.XmlNamespaceBinding),
                binding.span,
                MaterializationRelation.Generated,
            )
        }
        val attributes = data.attributes
        if (attributes.size != input.attributes.size) {
            throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
        }
        for ((inputAttribute, attribute) in input.attributes.zip(attributes)) {
            push(
                document.authority.nodeRef(attribute.ordinal, NodeRole.XmlAttribute),
                attribute.span,
                MaterializationRelation.Direct,
            )
            val expandedAttribute = attribute.expanded
                ?: throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
            val attrNameMatches = when {
                inputAttribute.namespace != null && expandedAttribute.namespace != null ->
                    inputAttribute.namespace == expandedAttribute.namespace

                inputAttribute.namespace == null && expandedAttribute.namespace == null -> true
                else -> false
            }
            if (!attrNameMatches ||
                expandedAttribute.local != inputAttribute.local ||
                attribute.normalizedValue != inputAttribute.value
            ) {
                throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
            }
        }
        val children = data.children
        if (children.size != input.content.size) {
            throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
        }
        for ((contentInput, childIndex) in input.content.zip(children)) {
            val child = XmlContentItem(document, childIndex)
            when (contentInput) {
                is ContentRecord.Element -> {
                    val childElement = child.element()
                        ?: throw MaterializationException(
                            MaterializationFailureKind.FORMATION_FAILED,
                        )
                    element(contentInput.element, childElement)
                }
                is ContentRecord.Text -> {
                    val text = child.text()
                        ?: throw MaterializationException(
                            MaterializationFailureKind.FORMATION_FAILED,
                        )
                    push(
                        document.authority.nodeRef(text.ordinal, NodeRole.XmlText),
                        text.span,
                        MaterializationRelation.Direct,
                    )
                    var semantic = StringBuilder()
                    for (fragment in contentInput.fragments) {
                        when (fragment) {
                            is FragmentRecord.Literal -> pushNormalized(semantic, fragment.text)
                            is FragmentRecord.CharacterReference ->
                                semantic.append(fragment.resolved)

                            is FragmentRecord.PredefinedEntity,
                            is FragmentRecord.GeneralEntity,
                            -> pushNormalized(
                                semantic,
                                (fragment as? FragmentRecord.PredefinedEntity)
                                    ?.resolved
                                    ?: (fragment as FragmentRecord.GeneralEntity).resolved,
                            )
                        }
                        push(
                            document.authority.nodeRef(text.ordinal, NodeRole.XmlEntityReference),
                            text.fragments.firstOrNull()?.span ?: text.span,
                            MaterializationRelation.Direct,
                        )
                    }
                    if (textSemantic(text) != semantic.toString()) {
                        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
                    }
                }
                is ContentRecord.Cdata -> {
                    val cdata = child.cdata()
                        ?: throw MaterializationException(
                            MaterializationFailureKind.FORMATION_FAILED,
                        )
                    push(
                        document.authority.nodeRef(cdata.ordinal, NodeRole.XmlCdata),
                        cdata.span,
                        MaterializationRelation.Direct,
                    )
                    if (cdata.text != contentInput.text) {
                        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
                    }
                }
                is ContentRecord.Comment -> {
                    val comment = child.comment()
                        ?: throw MaterializationException(
                            MaterializationFailureKind.FORMATION_FAILED,
                        )
                    push(
                        document.authority.nodeRef(comment.ordinal, NodeRole.XmlComment),
                        comment.span,
                        MaterializationRelation.Direct,
                    )
                    if (comment.text != contentInput.text) {
                        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
                    }
                }
                is ContentRecord.ProcessingInstruction -> {
                    val pi = child.processingInstruction()
                        ?: throw MaterializationException(
                            MaterializationFailureKind.FORMATION_FAILED,
                        )
                    push(
                        document.authority.nodeRef(pi.ordinal, NodeRole.XmlProcessingInstruction),
                        pi.span,
                        MaterializationRelation.Direct,
                    )
                    if (pi.target != contentInput.target ||
                        pi.content?.second != contentInput.content
                    ) {
                        throw MaterializationException(MaterializationFailureKind.FORMATION_FAILED)
                    }
                }
            }
        }
    }
}

/** XML 1.0 line-end normalization for one fragment: CRLF and CR become LF
 * (materialization.rs:1212-1226). */
private fun pushNormalized(out: StringBuilder, text: String) {
    var index = 0
    while (index < text.length) {
        val c = text[index]
        when (c) {
            '\r' -> {
                out.append('\n')
                if (index + 1 < text.length && text[index + 1] == '\n') {
                    index += 1
                }
            }
            else -> out.append(c)
        }
        index += 1
    }
}
